USE [baza-zamowien]

CREATE TABLE ZAMOWIENIA (
	ID_ZAMOWIENIA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	DATA_UTWORZENIA DATE NOT NULL,
	NR_TELEFONU VARCHAR(10) NOT NULL
);

CREATE TABLE DANIA (
	ID_DANIA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NAZWA VARCHAR(100) NOT NULL,
	CENA FLOAT NOT NULL,
)

CREATE TABLE REKLAMY (
	ID_REKLAMY INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	KOSZT FLOAT,
	SERWIS_REKLAMOWY VARCHAR(100) NOT NULL,
	DATA_ROZPOCZECIA DATE NOT NULL,
	DATA_ZAKONCZENIA DATE NOT NULL,
	ID_DANIA INT NOT NULL REFERENCES DANIA(ID_DANIA)
);

CREATE TABLE PRZEDMIOTY_ZAMOWIEN (
	ID_PRZEDMIOTU_ZAMOWIENIA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ID_DANIA INT NOT NULL REFERENCES DANIA(ID_DANIA),
	LICZBA INT NOT NULL,
	ID_ZAMOWIENIA INT NOT NULL REFERENCES ZAMOWIENIA(ID_ZAMOWIENIA)
);

CREATE TABLE PROMOCJE (
	ID_PROMOCJI INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	WARTOSC INT NOT NULL,
	DATA_ROZPOCZECIA DATE NOT NULL,
	DATA_ZAKONCZENIA DATE NOT NULL,
	ID_DANIA INT NOT NULL REFERENCES DANIA(ID_DANIA)
)